//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaysSince.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaysSince.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Since.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected Date.
        /// </summary>
        public static string chkBoxSaveSelectedDate {
            get {
                return ResourceManager.GetString("chkBoxSaveSelectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Date On Live Tile.
        /// </summary>
        public static string chkBoxShowDateOnLiveTile {
            get {
                return ResourceManager.GetString("chkBoxShowDateOnLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date:.
        /// </summary>
        public static string dtPickerFromDate {
            get {
                return ResourceManager.GetString("dtPickerFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Since.
        /// </summary>
        public static string dtPickerHdrDaySince {
            get {
                return ResourceManager.GetString("dtPickerHdrDaySince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date:.
        /// </summary>
        public static string dtPickerToDate {
            get {
                return ResourceManager.GetString("dtPickerToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Since.
        /// </summary>
        public static string PivotTitle {
            get {
                return ResourceManager.GetString("PivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God grant me the serenity to accept the things I cannot change, the courage to change the things I can and the wisdom to know the difference..
        /// </summary>
        public static string prySerenity {
            get {
                return ResourceManager.GetString("prySerenity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, I pray I may continue: To grow in understanding and effectiveness; To take daily spot check inventories of myself; To correct mistakes when I make them; To take responsibility for my actions; To be ever aware of my negative and self-defeating attitudes and behaviors; To keep my willfulness in check; To always remember I need Your help; To keep love and tolerance of others as my code; And to continue in daily prayer how I can best serve You, My Higher Power..
        /// </summary>
        public static string pryStep10Prayer {
            get {
                return ResourceManager.GetString("pryStep10Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, I pray to keep my connection with You open and clear from the confusion of daily life. Through my prayers and meditation I ask especially for freedom from self-will, rationalization, and wishful thinking. I pray for the guidance of correct thought and positive action. Your will, Higher Power, not mine, be done..
        /// </summary>
        public static string pryStep11Prayer {
            get {
                return ResourceManager.GetString("pryStep11Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, my spiritual awakening continues to unfold. The help I have received I shall pass on and give to others, both in and out of the Fellowship. For this opportunity I am grateful. I pray most humbly to continue walking day by day on the road of spiritual progress. I pray for the inner strength and wisdom to practice the principles of this way of life in all I do and say. I need You, my friends, and the program every hour of every day. This is a better way to live..
        /// </summary>
        public static string pryStep12Prayer {
            get {
                return ResourceManager.GetString("pryStep12Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, my name is ____. I&apos;m a real alcoholic... and I need your help today..
        /// </summary>
        public static string pryStep1Prayer {
            get {
                return ResourceManager.GetString("pryStep1Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, I&apos;m standing at the turning point right now. Give me your protection and care as I abandon myself to you and give up my old ways and my old ideas just for today..
        /// </summary>
        public static string pryStep2Prayer {
            get {
                return ResourceManager.GetString("pryStep2Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, I offer myself to Thee to build with me and to do with me as Thou wilt. Relieve me of the bondage of self, that I may better do Thy will. Take away my difficulties, that victory over them may bear witness to those I would help of Thy Power, Thy Love, and Thy Way of life. May I do Thy will always..
        /// </summary>
        public static string pryStep3Prayer {
            get {
                return ResourceManager.GetString("pryStep3Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, It is I who has made my life a mess. I have done it, but I cannot undo it. My mistakes are mine and I will begin a searching and fearless moral inventory. I will write down my wrongs but I will also include that which is good. I pray for the strength to complete the task..
        /// </summary>
        public static string pryStep4Prayer {
            get {
                return ResourceManager.GetString("pryStep4Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, My inventory has shown me who I am, Yet I ask for Your help in admitting my wrongs to another person and to You. Assure me, and be with me, in this step, for without this Step I cannot progress in my recovery. With Your help, I can do this, and I do it..
        /// </summary>
        public static string pryStep5Prayer {
            get {
                return ResourceManager.GetString("pryStep5Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, I am ready for Your help in removing from me the defects of character which I now realize are an obstacle to my recovery. Help me to continue being honest with myself and guide me toward spiritual and mental health..
        /// </summary>
        public static string pryStep6Prayer {
            get {
                return ResourceManager.GetString("pryStep6Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, I am now willing that you should have all of me, good and bad. I pray that you now remove from me every single defect of character which stands in the way of my usefulness to you and my fellows. Grant me strength, as I go out from here to do your bidding..
        /// </summary>
        public static string pryStep7Prayer {
            get {
                return ResourceManager.GetString("pryStep7Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, I ask Your help in making my list of all those I have harmed. I will take responsibility for my mistakes and be forgiving to others as You are forgiving to me. Grant me the willingness to begin my restitution. This I pray..
        /// </summary>
        public static string pryStep8Prayer {
            get {
                return ResourceManager.GetString("pryStep8Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Higher Power, I pray for the right attitude to make my amends, being ever mindful not to harm others in the process. I ask for Your guidance in making indirect amends. Most important, I will continue to make amends by staying abstinent, helping others and growing in spiritual progress..
        /// </summary>
        public static string pryStep9Prayer {
            get {
                return ResourceManager.GetString("pryStep9Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Diff.
        /// </summary>
        public static string pvtHdrDateDiff {
            get {
                return ResourceManager.GetString("pvtHdrDateDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Since.
        /// </summary>
        public static string pvtHdrDaySince {
            get {
                return ResourceManager.GetString("pvtHdrDaySince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayers.
        /// </summary>
        public static string pvtHdrPrayers {
            get {
                return ResourceManager.GetString("pvtHdrPrayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 12 Steps.
        /// </summary>
        public static string pvtHdrThe12Steps {
            get {
                return ResourceManager.GetString("pvtHdrThe12Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 12 Traditions.
        /// </summary>
        public static string pvtHdrThe12Traditions {
            get {
                return ResourceManager.GetString("pvtHdrThe12Traditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10th Step Prayer.
        /// </summary>
        public static string txt10thStepPrayer {
            get {
                return ResourceManager.GetString("txt10thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11th Step Prayer.
        /// </summary>
        public static string txt11thStepPrayer {
            get {
                return ResourceManager.GetString("txt11thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12th Step Prayer.
        /// </summary>
        public static string txt12thStepPrayer {
            get {
                return ResourceManager.GetString("txt12thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Step Prayer.
        /// </summary>
        public static string txt1stStepPrayer {
            get {
                return ResourceManager.GetString("txt1stStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Step Prayer.
        /// </summary>
        public static string txt2ndStepPrayer {
            get {
                return ResourceManager.GetString("txt2ndStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Step Prayer.
        /// </summary>
        public static string txt3rdStepPrayer {
            get {
                return ResourceManager.GetString("txt3rdStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Step Prayer.
        /// </summary>
        public static string txt4thStepPrayer {
            get {
                return ResourceManager.GetString("txt4thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th Step Prayer.
        /// </summary>
        public static string txt5thStepPrayer {
            get {
                return ResourceManager.GetString("txt5thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6th Step Prayer.
        /// </summary>
        public static string txt6thStepPrayer {
            get {
                return ResourceManager.GetString("txt6thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7th Step Prayer.
        /// </summary>
        public static string txt7thStepPrayer {
            get {
                return ResourceManager.GetString("txt7thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8th Step Prayer.
        /// </summary>
        public static string txt8thStepPrayer {
            get {
                return ResourceManager.GetString("txt8thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9th Step Prayer.
        /// </summary>
        public static string txt9thStepPrayer {
            get {
                return ResourceManager.GetString("txt9thStepPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string txtAbout {
            get {
                return ResourceManager.GetString("txtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for this application have been disabled by the user..
        /// </summary>
        public static string txtBackAgentsDisabled {
            get {
                return ResourceManager.GetString("txtBackAgentsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNS Error: The action is disabled.
        /// </summary>
        public static string txtBNSError {
            get {
                return ResourceManager.GetString("txtBNSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Caralex.
        /// </summary>
        public static string txtCopyrightCaralex {
            get {
                return ResourceManager.GetString("txtCopyrightCaralex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback on Days Since app v1.2.0.0.
        /// </summary>
        public static string txtEmailFeedback {
            get {
                return ResourceManager.GetString("txtEmailFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        public static string txtEmailUs {
            get {
                return ResourceManager.GetString("txtEmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback is always appreciated, so feel free to drop us a line:.
        /// </summary>
        public static string txtFeedbackIsAlways {
            get {
                return ResourceManager.GetString("txtFeedbackIsAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the application is not launched for 2 weeks, the Live Tile will stop updating. This is a Windows Phone OS restriction. You must re-launch, re-select your date from &apos;Days Since&apos; and re-select the &apos;Show on Live Tile&apos; checkbox again..
        /// </summary>
        public static string txtIfTheAppIsNotLaunched {
            get {
                return ResourceManager.GetString("txtIfTheAppIsNotLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this app, please review it:.
        /// </summary>
        public static string txtIfYouLikeThisApp {
            get {
                return ResourceManager.GetString("txtIfYouLikeThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information in this application is not collected or distributed and is meant only for your viewing pleasure..
        /// </summary>
        public static string txtInfoInThisAppNotCollected {
            get {
                return ResourceManager.GetString("txtInfoInThisAppNotCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Live Tile gets updated every half hour after power-up.  So if the &apos;Days Since&apos; count is off, wait half an hour for it to update correctly..
        /// </summary>
        public static string txtLiveTileGetsUpdated {
            get {
                return ResourceManager.GetString("txtLiveTileGetsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNS Error: The maximum number of ScheduledActions of this type have already been added..
        /// </summary>
        public static string txtMaxScheduledActions {
            get {
                return ResourceManager.GetString("txtMaxScheduledActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string txtNotesColon {
            get {
                return ResourceManager.GetString("txtNotesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Since Tile Update Task.
        /// </summary>
        public static string txtPeriodicTaskDesc {
            get {
                return ResourceManager.GetString("txtPeriodicTaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review in Marketplace.
        /// </summary>
        public static string txtReviewInMarketplace {
            get {
                return ResourceManager.GetString("txtReviewInMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serenity Prayer.
        /// </summary>
        public static string txtSerenityPrayer {
            get {
                return ResourceManager.GetString("txtSerenityPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string txtStep1 {
            get {
                return ResourceManager.GetString("txtStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 10.
        /// </summary>
        public static string txtStep10 {
            get {
                return ResourceManager.GetString("txtStep10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continued to take personal inventory and when we were wrong promptly admitted it..
        /// </summary>
        public static string txtStep10Content {
            get {
                return ResourceManager.GetString("txtStep10Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 11.
        /// </summary>
        public static string txtStep11 {
            get {
                return ResourceManager.GetString("txtStep11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sought through prayer and meditation to improve our conscious contact with God, as we understood Him, praying only for knowledge of His will for us and the power to carry that out..
        /// </summary>
        public static string txtStep11Content {
            get {
                return ResourceManager.GetString("txtStep11Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 12.
        /// </summary>
        public static string txtStep12 {
            get {
                return ResourceManager.GetString("txtStep12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having had a spiritual awakening as the result of these Steps, we tried to carry this message to other alcoholics, and to practice these principles in all our affairs..
        /// </summary>
        public static string txtStep12Content {
            get {
                return ResourceManager.GetString("txtStep12Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We admitted we were powerless over alcohol - that our lives had become unmanageable..
        /// </summary>
        public static string txtStep1Content {
            get {
                return ResourceManager.GetString("txtStep1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string txtStep2 {
            get {
                return ResourceManager.GetString("txtStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came to believe that a Power greater than ourselves could restore us to sanity..
        /// </summary>
        public static string txtStep2Content {
            get {
                return ResourceManager.GetString("txtStep2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        public static string txtStep3 {
            get {
                return ResourceManager.GetString("txtStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made a decision to turn our will and our lives over to the care of God as we understood Him..
        /// </summary>
        public static string txtStep3Content {
            get {
                return ResourceManager.GetString("txtStep3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4.
        /// </summary>
        public static string txtStep4 {
            get {
                return ResourceManager.GetString("txtStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made a searching and fearless moral inventory of ourselves..
        /// </summary>
        public static string txtStep4Content {
            get {
                return ResourceManager.GetString("txtStep4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5.
        /// </summary>
        public static string txtStep5 {
            get {
                return ResourceManager.GetString("txtStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admitted to God, to ourselves and to another human being the exact nature of our wrongs..
        /// </summary>
        public static string txtStep5Content {
            get {
                return ResourceManager.GetString("txtStep5Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 6.
        /// </summary>
        public static string txtStep6 {
            get {
                return ResourceManager.GetString("txtStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were entirely ready to have God remove all these defects of character..
        /// </summary>
        public static string txtStep6Content {
            get {
                return ResourceManager.GetString("txtStep6Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 7.
        /// </summary>
        public static string txtStep7 {
            get {
                return ResourceManager.GetString("txtStep7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humbly asked Him to remove our shortcomings..
        /// </summary>
        public static string txtStep7Content {
            get {
                return ResourceManager.GetString("txtStep7Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 8.
        /// </summary>
        public static string txtStep8 {
            get {
                return ResourceManager.GetString("txtStep8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made a list of all persons we had harmed, and became willing to make amends to them all..
        /// </summary>
        public static string txtStep8Content {
            get {
                return ResourceManager.GetString("txtStep8Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 9.
        /// </summary>
        public static string txtStep9 {
            get {
                return ResourceManager.GetString("txtStep9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made direct amends to such people wherever possible, except when to do so would injure them or others..
        /// </summary>
        public static string txtStep9Content {
            get {
                return ResourceManager.GetString("txtStep9Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 1.
        /// </summary>
        public static string txtTradition1 {
            get {
                return ResourceManager.GetString("txtTradition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 10.
        /// </summary>
        public static string txtTradition10 {
            get {
                return ResourceManager.GetString("txtTradition10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcoholics Anonymous has no opinion on outside issues; hence the A.A. name ought never be drawn into public controversy..
        /// </summary>
        public static string txtTradition10Content {
            get {
                return ResourceManager.GetString("txtTradition10Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 11.
        /// </summary>
        public static string txtTradition11 {
            get {
                return ResourceManager.GetString("txtTradition11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our public relations policy is based on attraction rather than promotion; we need always maintain personal anonymity at the level of press, radio, and films..
        /// </summary>
        public static string txtTradition11Content {
            get {
                return ResourceManager.GetString("txtTradition11Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 12.
        /// </summary>
        public static string txtTradition12 {
            get {
                return ResourceManager.GetString("txtTradition12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymity is the spiritual foundation of all our Traditions, ever reminding us to place principles before personalities..
        /// </summary>
        public static string txtTradition12Content {
            get {
                return ResourceManager.GetString("txtTradition12Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our common welfare should come first; personal recovery depends upon A.A. unity..
        /// </summary>
        public static string txtTradition1Content {
            get {
                return ResourceManager.GetString("txtTradition1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 2.
        /// </summary>
        public static string txtTradition2 {
            get {
                return ResourceManager.GetString("txtTradition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For our group purpose there is but one ultimate authority—a loving God as He may express Himself in our group conscience. Our leaders are but trusted servants; they do not govern..
        /// </summary>
        public static string txtTradition2Content {
            get {
                return ResourceManager.GetString("txtTradition2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 3.
        /// </summary>
        public static string txtTradition3 {
            get {
                return ResourceManager.GetString("txtTradition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only requirement for A.A. membership is a desire to stop drinking..
        /// </summary>
        public static string txtTradition3Content {
            get {
                return ResourceManager.GetString("txtTradition3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 4.
        /// </summary>
        public static string txtTradition4 {
            get {
                return ResourceManager.GetString("txtTradition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each group should be autonomous except in matters affecting other groups or A.A. as a whole..
        /// </summary>
        public static string txtTradition4Content {
            get {
                return ResourceManager.GetString("txtTradition4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 5.
        /// </summary>
        public static string txtTradition5 {
            get {
                return ResourceManager.GetString("txtTradition5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each group has but one primary purpose—to carry its message to the alcoholic who still suffers..
        /// </summary>
        public static string txtTradition5Content {
            get {
                return ResourceManager.GetString("txtTradition5Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 6.
        /// </summary>
        public static string txtTradition6 {
            get {
                return ResourceManager.GetString("txtTradition6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An A.A. group ought never endorse, finance, or lend the A.A. name to any related facility or outside enterprise, lest problems of money, property, and prestige divert us from our primary purpose..
        /// </summary>
        public static string txtTradition6Content {
            get {
                return ResourceManager.GetString("txtTradition6Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 7.
        /// </summary>
        public static string txtTradition7 {
            get {
                return ResourceManager.GetString("txtTradition7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every A.A. group ought to be fully self-supporting, declining outside contributions..
        /// </summary>
        public static string txtTradition7Content {
            get {
                return ResourceManager.GetString("txtTradition7Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 8.
        /// </summary>
        public static string txtTradition8 {
            get {
                return ResourceManager.GetString("txtTradition8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcoholics Anonymous should remain forever nonprofessional, but our service centers may employ special workers..
        /// </summary>
        public static string txtTradition8Content {
            get {
                return ResourceManager.GetString("txtTradition8Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition 9.
        /// </summary>
        public static string txtTradition9 {
            get {
                return ResourceManager.GetString("txtTradition9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.A., as such, ought never be organized; but we may create service boards or committees directly responsible to those they serve..
        /// </summary>
        public static string txtTradition9Content {
            get {
                return ResourceManager.GetString("txtTradition9Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.2.0.0.
        /// </summary>
        public static string txtVersion {
            get {
                return ResourceManager.GetString("txtVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10: Developed from Chapter 6, &quot;Into Action&quot;, from pg 84 thru pg 85. (4th ed,).
        /// </summary>
        public static string txtWherePrayer10IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer10IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11: Developed from Chapter 6, &quot;Into Action&quot;, from pg 85 thru pg 88. (4th ed.).
        /// </summary>
        public static string txtWherePrayer11IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer11IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12: Developed from Chapter 7, &quot;Working With Others&quot;, from pg 89. (4th ed.).
        /// </summary>
        public static string txtWherePrayer12IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer12IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1: Developed from Chapter 3, &quot;More About Alcoholism&quot;, pg 30. (4th ed.).
        /// </summary>
        public static string txtWherePrayer1IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer1IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2: Developed from Chapter 5, &quot;How It Works&quot;, pg 59. (4th ed.).
        /// </summary>
        public static string txtWherePrayer2IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer2IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3: From Chapter 5, &quot;How It Works&quot;, pg 63. (4th ed.).
        /// </summary>
        public static string txtWherePrayer3IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer3IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4: Developed from chapter 5, &quot;How It Works&quot;, (4th ed)..
        /// </summary>
        public static string txtWherePrayer4IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer4IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5: Developed from chapter 6, &quot;Into Action&quot;, pg 72 thru pg 75. (4th ed)..
        /// </summary>
        public static string txtWherePrayer5IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer5IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6: Developed from Chapter 6, &quot;Into Action&quot;, From pg 76. (4th ed.).
        /// </summary>
        public static string txtWherePrayer6IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer6IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7: From Chapter 6, &quot;Into Action&quot;,. From pg 76:2. (4th ed)..
        /// </summary>
        public static string txtWherePrayer7IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer7IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8: Developed from Chapter 6, &quot;Into Action&quot;, from pg 76. (4th ed)..
        /// </summary>
        public static string txtWherePrayer8IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer8IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9: Developed from Chapter 6, &quot;Into Action&quot;, from pg 84 thru pg 85. (4th ed)..
        /// </summary>
        public static string txtWherePrayer9IsFrom {
            get {
                return ResourceManager.GetString("txtWherePrayer9IsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Where the prayers are from in the Big Book:.
        /// </summary>
        public static string txtWherePrayersAreFrom {
            get {
                return ResourceManager.GetString("txtWherePrayersAreFrom", resourceCulture);
            }
        }
    }
}
