//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaysSinceClassLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DaysSinceClassLibAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DaysSinceClassLibAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaysSinceClassLibrary.DaysSinceClassLibAppResources", typeof(DaysSinceClassLibAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Day.
        /// </summary>
        public static string txtDay {
            get {
                return ResourceManager.GetString("txtDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Day..
        /// </summary>
        public static string txtDayPeriod {
            get {
                return ResourceManager.GetString("txtDayPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Days.
        /// </summary>
        public static string txtDays {
            get {
                return ResourceManager.GetString("txtDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Month, .
        /// </summary>
        public static string txtMonthComma {
            get {
                return ResourceManager.GetString("txtMonthComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Months, .
        /// </summary>
        public static string txtMonthsComma {
            get {
                return ResourceManager.GetString("txtMonthsComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  day.
        /// </summary>
        public static string txtSpaceDay {
            get {
                return ResourceManager.GetString("txtSpaceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days.
        /// </summary>
        public static string txtSpaceDays {
            get {
                return ResourceManager.GetString("txtSpaceDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days .
        /// </summary>
        public static string txtSpaceDaysSpace {
            get {
                return ResourceManager.GetString("txtSpaceDaysSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  month, .
        /// </summary>
        public static string txtSpaceMonthCommaSpace {
            get {
                return ResourceManager.GetString("txtSpaceMonthCommaSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  months, .
        /// </summary>
        public static string txtSpaceMonthsCommaSpace {
            get {
                return ResourceManager.GetString("txtSpaceMonthsCommaSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  year, .
        /// </summary>
        public static string txtSpaceYearCommaSpace {
            get {
                return ResourceManager.GetString("txtSpaceYearCommaSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Year, .
        /// </summary>
        public static string txtYearComma {
            get {
                return ResourceManager.GetString("txtYearComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Years, .
        /// </summary>
        public static string txtYearsComma {
            get {
                return ResourceManager.GetString("txtYearsComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  years, .
        /// </summary>
        public static string txtYearsCommaSpace {
            get {
                return ResourceManager.GetString("txtYearsCommaSpace", resourceCulture);
            }
        }
    }
}
